#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0 OR MIT
set -CeEuo pipefail
IFS=$'\n\t'
trap -- 's=$?; printf >&2 "%s\n" "${0##*/}:${LINENO}: \`${BASH_COMMAND}\` exit with ${s}"; exit ${s}' ERR
trap -- 'printf >&2 "%s\n" "${0##*/}: trapped SIGINT"; exit 1' SIGINT

# shellcheck source-path=SCRIPTDIR
. "$(dirname -- "$0")"/shared.sh

if [[ $# -gt 0 ]]; then
  cat <<EOF
USAGE:
    $0
EOF
  exit 1
fi

# Spell check (if config exists)
if [[ -n "${TIDY_COLOR_ALWAYS}" ]]; then
  cspell() { command cspell --no-config-search --no-progress --no-summary --color "$@"; }
else
  cspell() { command cspell --no-config-search --no-progress --no-summary "$@"; }
fi
if [[ -e .cspell.json ]] || [[ -e .github/.cspell ]]; then
  info "spell checking"
  check_config .cspell.json
  project_dictionary=.github/.cspell/project-dictionary.txt
  has_rust=''
  if [[ -n "$(ls_files '*Cargo.toml')" ]]; then
    has_rust=1
    dependencies=''
    for manifest_path in $(ls_files '*Cargo.toml'); do
      if [[ "${manifest_path}" != "Cargo.toml" ]]; then
        workspace=$(tomlq -c '.workspace' "${manifest_path}")
        if [[ "${workspace}" == 'null' ]]; then
          continue
        fi
      fi
      m=$(cargo metadata --format-version=1 --no-deps --manifest-path "${manifest_path}" || true)
      if [[ -z "${m}" ]]; then
        continue # Ignore broken manifest
      fi
      dependencies+="$(jq -r '. as $metadata | .workspace_members[] as $id | $metadata.packages[] | select(.id == $id) | .dependencies[].name' <<<"${m}")"$'\n'
    done
    dependencies=$(LC_ALL=C sort -f -u <<<"${dependencies//[0-9_-]/$'\n'}")
  fi
  config_old=$(<.cspell.json)
  config_new=$({ grep -Ev '^ *//' <<<"${config_old}" || true; } | jq 'del(.dictionaries[] | select(index("organization-dictionary") | not)) | del(.dictionaryDefinitions[] | select(.name == "organization-dictionary" | not))')
  mkdir -p -- /tmp/tidy/.github
  ln -s -- "$(pwd)"/.github/.cspell /tmp/tidy/.github
  printf '%s\n' "${config_new}" >|/tmp/tidy/.cspell.json
  dependencies_words=''
  if [[ -n "${has_rust}" ]]; then
    dependencies_words=$({ cspell --config /tmp/tidy/.cspell.json stdin --words-only --unique <<<"${dependencies}" || true; } | LC_ALL=C sort -f)
    if [[ -n "${dependencies_words}" ]]; then
      dependencies_words=$'\n\n'"${dependencies_words}"
    fi
  fi
  all_words=$(ls_files | { grep -Fv "${project_dictionary}" || true; } | cspell --config /tmp/tidy/.cspell.json --file-list stdin --words-only --unique || true)
  all_words+=$'\n'$(ls_files | cspell --config /tmp/tidy/.cspell.json stdin --words-only --unique || true)
  cat >|.github/.cspell/rust-dependencies.txt <<EOF
# This file is @generated by ${TIDY_CALLER##*/}.
# It is not intended for manual editing.${dependencies_words}
EOF
  if [[ -z "${CI:-}" ]]; then
    REMOVE_UNUSED_WORDS=1
  fi
  if [[ -z "${REMOVE_UNUSED_WORDS:-}" ]]; then
    check_diff .github/.cspell/rust-dependencies.txt
  fi
  if ! grep -Fq '.github/.cspell/rust-dependencies.txt linguist-generated' .gitattributes; then
    error "you may want to mark .github/.cspell/rust-dependencies.txt linguist-generated"
  fi

  # Check file names.
  info "running \`git ls-files | cspell stdin --no-progress --no-summary --show-context\`"
  if ! ls_files | cspell stdin --show-context; then
    error "spellcheck failed: please fix uses of below words in file names or add to ${project_dictionary} if correct"
    printf '=======================================\n'
    { ls_files | cspell stdin --words-only || true; } | sed -E "s/'s$//g" | LC_ALL=C sort -f -u
    printf '=======================================\n\n'
  fi
  # Check file contains.
  info "running \`git ls-files | cspell --file-list stdin --no-progress --no-summary\`"
  if ! ls_files | cspell --file-list stdin; then
    error "spellcheck failed: please fix uses of below words or add to ${project_dictionary} if correct"
    printf '=======================================\n'
    { ls_files | cspell --file-list stdin --words-only || true; } | sed -E "s/'s$//g" | LC_ALL=C sort -f -u
    printf '=======================================\n\n'
  fi

  # Make sure the project-specific dictionary does not contain duplicated words.
  for dictionary in .github/.cspell/*.txt; do
    if [[ "${dictionary}" == "${project_dictionary}" ]]; then
      continue
    fi
    dup=$(sed -E 's/#.*//g; s/^[ \t]+//g; s/\/[ \t]+$//g; /^$/d' "${project_dictionary}" "${dictionary}" | LC_ALL=C sort -f | LC_ALL=C uniq -d -i)
    if [[ -n "${dup}" ]]; then
      error "duplicated words in dictionaries; please remove the following words from ${project_dictionary}"
      print_fenced "${dup}"$'\n'
    fi
  done

  # Make sure the project-specific dictionary does not contain unused words.
  if [[ -n "${REMOVE_UNUSED_WORDS:-}" ]]; then
    grep_args=()
    while IFS= read -r word; do
      if ! grep -Eqi "^${word}$" <<<"${all_words}"; then
        grep_args+=(-e "^[ \t]*${word}[ \t]*(#.*|$)")
      fi
    done < <(sed -E 's/#.*//g; s/^[ \t]+//g; s/\/[ \t]+$//g; /^$/d' "${project_dictionary}")
    if [[ ${#grep_args[@]} -gt 0 ]]; then
      info "removing unused words from ${project_dictionary}"
      info "please commit changes made by the removal above"
      res=$(grep -Ev "${grep_args[@]}" "${project_dictionary}" || true)
      if [[ -n "${res}" ]]; then
        printf '%s\n' "${res}" >|"${project_dictionary}"
      else
        printf '' >|"${project_dictionary}"
      fi
    fi
  else
    unused=''
    while IFS= read -r word; do
      if ! grep -Eqi "^${word}$" <<<"${all_words}"; then
        unused+="${word}"$'\n'
      fi
    done < <(sed -E 's/#.*//g; s/^[ \t]+//g; s/\/[ \t]+$//g; /^$/d' "${project_dictionary}")
    if [[ -n "${unused}" ]]; then
      error "unused words in dictionaries; please remove the following words from ${project_dictionary} or run ${TIDY_CALLER} locally"
      print_fenced "${unused}"
    fi
  fi
  printf '\n'
else
  check_unused "spell checking" '*.cspell*'
fi

if [[ -n "${should_fail:-}" ]]; then
  exit 1
fi
