name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@5f549ff6b21e9a853f5f613784d5db27746fd2bc # main
    permissions:
      contents: write # for creating branch for pr
      pull-requests: write # unused (used in `codegen-automerge: true` case)
      security-events: write # for github/codeql-action/*
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # --------------------------------------------------------------------
          # binutils/objdump
          - package: binutils
          - package: binutils
            os: ubuntu-24.04-arm
          # --------------------------------------------------------------------
          # build-base
          - package: build-base
            distro: ubuntu:18.04
          - package: build-base
            distro: ubuntu:20.04
          - package: build-base
            distro: ubuntu:22.04
          - package: build-base
            distro: ubuntu:24.04 # latest
          - package: build-base
            distro: ubuntu:26.04
          - package: build-base
            distro: ubuntu:25.10 # rolling
          - package: build-base
            distro: debian:11
          - package: build-base
            distro: debian:12
          - package: build-base
            distro: debian:13 # latest
          - package: build-base
            distro: debian:testing
          - package: build-base
            distro: alpine:3.23 # latest
          - package: build-base
            distro: alpine:edge
          # --------------------------------------------------------------------
          # downloader
          - package: downloader
          # --------------------------------------------------------------------
          # qemu-user
          - package: qemu-user
          # --------------------------------------------------------------------
          # tidy
          - package: tidy
          # --------------------------------------------------------------------
          # valgrind
          - package: valgrind
            arch: amd64
          - package: valgrind
            arch: arm64
          - package: valgrind
            arch: armhf
          - package: valgrind
            arch: i386
          - package: valgrind
            arch: ppc64el
          - package: valgrind
            arch: riscv64
          - package: valgrind
            arch: s390x
          # --------------------------------------------------------------------
          # vnc
          - package: vnc
            distro: ubuntu:14.04
          # TODO: (x-terminal-emulator:80): GLib-CRITICAL **: g_shell_parse_argv: assertion 'command_line != NULL' failed
          # - package: vnc
          #   distro: ubuntu:16.04
          - package: vnc
            distro: ubuntu:18.04
          - package: vnc
            distro: ubuntu:20.04
          - package: vnc
            distro: ubuntu:22.04
          - package: vnc
            distro: ubuntu:24.04 # latest
          - package: vnc
            distro: ubuntu:26.04
          - package: vnc
            distro: debian:11
          - package: vnc
            distro: debian:12
          - package: vnc
            distro: debian:13 # latest
    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
    timeout-minutes: 60
    permissions:
      packages: write # for pushing to ghcr
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: taiki-e/github-actions/setup-docker@5f549ff6b21e9a853f5f613784d5db27746fd2bc # main # zizmor: ignore[stale-action-refs]
      - run: |
          docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin <<<"${GITHUB_TOKEN}"
          printf 'PUSH_TO_GHCR=1\n' >>"${GITHUB_ENV}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
      - run: |
          "${PACKAGE}"/build-docker.sh ${DISTRO:-} ${ARCH:-}
        env:
          PACKAGE: ${{ matrix.package }}
          DISTRO: ${{ matrix.distro }}
          ARCH: ${{ matrix.arch }}
          QEMU_VERSION: ${{ matrix.qemu-version }}
          QEMU_TARGET: ${{ matrix.qemu-target }}
      - run: TIDY_DEV=1 tools/tidy.sh
        if: matrix.package == 'tidy'

  manifest:
    if: github.repository_owner == 'taiki-e' && (github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      packages: write # for pushing to ghcr
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - run: |
          docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin <<<"${GITHUB_TOKEN}"
          printf 'PUSH_TO_GHCR=1\n' >>"${GITHUB_ENV}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
      - run: binutils/docker-manifest.sh
