name: Docker

permissions:
  contents: read
  packages: write

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  docker:
    strategy:
      matrix:
        package:
          - build-base
        distro:
          - ubuntu
          - alpine
        include:
          - package: downloader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          echo "PUSH_TO_GHCR=1" >> "${GITHUB_ENV}"
        if: github.repository_owner == 'taiki-e' && (github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
      - run: ${{ matrix.package }}/build-docker.sh
        env:
          DISTRO: ${{ matrix.distro }}
